-- Captação de evento/empresas, status de e-mail do Mapa e proteção contra abuso.
-- Migração idempotente para produção.
create extension if not exists pgcrypto;

alter table public.map_sessions add column if not exists owner_notification_status text not null default 'pending';
alter table public.map_sessions add column if not exists owner_notified_at timestamptz;

create table if not exists public.interest_leads (
  id uuid primary key default gen_random_uuid(),
  contact_id uuid not null references public.contacts(id) on delete cascade,
  interest_type text not null check (interest_type in ('event','corporate')),
  company text,
  interest text,
  source text,
  page_url text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  privacy_version text not null,
  email_status text not null default 'pending' check (email_status in ('pending','sent','failed')),
  email_sent_at timestamptz,
  owner_notification_status text not null default 'pending' check (owner_notification_status in ('pending','sent','failed','disabled')),
  owner_notified_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.submission_rate_limits (
  id bigint generated by default as identity primary key,
  scope text not null,
  fingerprint text not null,
  created_at timestamptz not null default now()
);

create index if not exists interest_leads_created_idx on public.interest_leads(created_at desc);
create index if not exists interest_leads_type_idx on public.interest_leads(interest_type);
create index if not exists submission_rate_limits_lookup_idx on public.submission_rate_limits(scope, fingerprint, created_at desc);

alter table public.interest_leads enable row level security;
alter table public.submission_rate_limits enable row level security;

-- Sem policies para anon/authenticated. O navegador não acessa estas tabelas.
